# Generated by Django 3.1.7 on 2021-04-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackList', '0002_auto_20210422_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='date',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
