# Generated by Django 3.1.7 on 2021-04-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=30)),
                ('telephone', models.CharField(max_length=30)),
            ],
        ),
    ]
