# Generated by Django 3.1.7 on 2021-04-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackList', '0004_auto_20210423_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='date',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
